### ISSUE TITLE
Installation issue on Linux

### ISSUE THREAD

**Issue by stephaniewankowicz** [keiserlab/LUNA#44]
I have followed the instructions on your readme (create conda env), activate, but when I run pip install luna, I get:

Collecting luna
  Downloading luna-0.13.0.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/scratch/swankowicz/pip-install-3ci9n7li/luna_04662606934745139f71d50467b3f1c4/setup.py", line 28, in <module>
          from luna.version import version
        File "/scratch/swankowicz/pip-install-3ci9n7li/luna_04662606934745139f71d50467b3f1c4/luna/__init__.py", line 2, in <module>
          from luna.projects import Project, LocalProject
        File "/scratch/swankowicz/pip-install-3ci9n7li/luna_04662606934745139f71d50467b3f1c4/luna/projects.py", line 9, in <module>
          from scipy.special import comb
      ModuleNotFoundError: No module named 'scipy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I am also getting this error with pdbecif. After installing that, pip install Luna worked.

**Comment by alexandrefassio** [comment]
Hi @stephaniewankowicz,

Good catch! Thanks for letting me know about this bug. 

In fact, I forgot to add **pdbecif** to the env file after the last update. The only surprising thing is that **scipy* was not automatically recognized and installed together with other dependencies. I'll add it in any case so that other people don't face the same issue as you did.

For curiosity, which SO are you using? Maybe this issue with scipy not being automatically installed is due to different SO versions.

Anyway...I understood from your message that you could already solve the problem, right!?

bests
