### ISSUE TITLE
Title of outputs containing ":" 

### ISSUE THREAD

**Issue by Nsaima** [keiserlab/LUNA#45]
Hello, 
In the interactions outputs all the csv are named the following  : protein:ligand.csv. The ":" leads to a file that i am unable to read. I don't know where exactly i can modify the output name. Thank you

**Comment by alexandrefassio** [comment]
Hi @Nsaima 

Just for curiosity, are you using Windows?

Regarding your question, it depends on how you're using LUNA: programmatically, i.e., developing your own Python scripts; or using LUNA with the run.py script.

For the first option, when you create an entry using some of the classes in '[luna.mol.entry](https://github.com/keiserlab/LUNA/blob/master/luna/mol/entry.py)', you can define the parameter **sep**, which controls which separator will be used to name an entry. By default, LUNA uses ':', that's why your files are named 'protein:ligand.csv'. If you want to use the separator '+', for instance, just pass **sep='+'** and your files will be named 'protein+ligand.csv'. See below:

```
MolFileEntry.from_mol_file(pdb_id='protein', 
                           mol_id='ligand', 
                           mol_file='ligand.mol2',
                           is_multimol_file=False, 
                           sep='+')
```

For the run.py script, there's the argument **--esep**, which you can use to define the separator you want to use in the same way as I explained above. **However, this doesn't work on LUNA up to version 0.13.0**. After verifying your question, I noticed **--esep** didn't work for complexes where protein and ligands are in separate files (your case, presumably). So, I just amended the code so that this argument is always used. **Please, update LUNA to version 0.13.1, and give it a try**. Both PIP and Git are now in version 0.13.1.

Let me know if you have any additional questions.
bests

**Comment by alexandrefassio** [comment]
Hi @Nsaima,

Feel free to reopen this issue in case you still need some help on this.

bests
